# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 32001
      hostPort: 32001
      protocol: TCP
    - containerPort: 32002
      hostPort: 32002
      protocol: TCP
- role: worker
  extraPortMappings:
    - containerPort: 32003
      hostPort: 32003
      protocol: TCP
- role: worker
  extraPortMappings:
    - containerPort: 32004
      hostPort: 32004
      protocol: TCP
